language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-21.1.2
    - android-21
    - extra-android-support
    - extra-android-m2repository
env:
  global:
    - TERM=dumb
before_script:
  - export DATE=$(date)
  - export VERSION=$(date --date="$DATE" +'%Y%m%d%H%M%S')
script:
  - sed -i -r -e "s/(android:versionCode=\")[0-9]+(\")/\1$VERSION\2/g"
              -e "s/(android:versionName=\"[0-9.]+)(\")/\1-dev-$VERSION\2/g"
              AndroidManifest.xml
  - mv src/me/sheimi/sgit src/me/sheimi/sgit_dev
  - find . -type f -exec sed -i "s/me\.sheimi\.sgit/me\.sheimi\.sgit_dev/g" '{}' \;
  - find src/main/res -type f -exec sed -i -r 's/(<string name="app_name">SGit)(<\/string>)/\1 Dev\2/g' '{}' \;
  - cd ..
after_success:
  - curl -sSL "https://raw.githubusercontent.com/h5bp-bot/scripts/0.6.1/update_site_branch.sh" |
         bash -s -- --commands "true"
                    --commit-message "Build generated on $DATE by Travis [ci skip]"
                    --directory "build"
                    --distribution-branch "build"
                    --source-branch "dev"
